const actionLabels: Record<string, string> = {
  "platform.tenant.created": "创建公司",
  "platform.tenant.status_changed": "公司状态变更",
  "platform.tenant.admin_invitation_renewed": "重新邀请首位管理员",
  "platform.tenant.admin_phone_corrected": "更正首位管理员手机号",
  "platform.template.applied": "应用业务模板",
  "invitation.created": "邀请成员",
  "invitation.accepted": "接受邀请",
  "invitation.declined": "拒绝邀请",
  "invitation.revoked": "撤销邀请",
  "invitation.resent": "重新邀请",
  "membership.status_changed": "变更成员状态",
  "membership.role_changed": "变更成员角色",
  "membership.admin_handoff": "管理员交接",
  "membership.offboarded": "离职交接",
  "membership.object_access_changed": "调整业务表权限",
  "record.created": "创建业务记录",
  "record.updated": "更新业务记录",
  "record.deleted": "删除业务记录",
  "record.published": "发布业务记录",
  "record.draft_saved": "保存草稿业务记录",
  "object.permissions_updated": "更新业务表权限",
  "object.field_created": "新增业务字段",
  "object.field_updated": "更新业务字段",
  "demo.company.seeded": "初始化演示公司",
  "attachment.created": "上传记录附件",
  "attachment.deleted": "删除记录附件",
  "record.relation_added": "关联业务记录",
  "record.relation_removed": "移除业务关联",
  "object.created": "创建业务表",
  "object.updated": "更新业务表",
  "object.deleted": "删除业务表",
  "object.published": "发布业务表",
  "object.draft_saved": "保存草稿业务表",
  "dashboard.created": "创建仪表盘",
  "dashboard.updated": "更新仪表盘",
  "dashboard.deleted": "删除仪表盘",
  "dashboard.published": "发布仪表盘",
  "dashboard.draft_saved": "保存草稿仪表盘",
  "platform.template.created": "创建业务模板",
  "platform.template.updated": "更新业务模板",
  "platform.template.deleted": "删除业务模板",
  "platform.template.published": "发布业务模板",
  "platform.template.draft_saved": "保存草稿业务模板",
  "follow_up.created": "创建跟进",
  "follow_up.completed": "完成跟进",
  "follow_up.cancelled": "取消跟进",
  "follow_up.rescheduled": "改期跟进",
  "follow_up.reassigned": "转派跟进",
  "dashboard.defaults_updated": "设置默认工作台",
  "dashboard.order_updated": "调整工作台顺序",
  "object.draft_deleted": "删除业务表草稿",
  "object.order_updated": "调整业务表顺序",
  "platform.admin.granted": "授予平台管理员",
  "record.activity_created": "新增记录跟进",
  "record.exported": "导出业务记录",

  TENANT_CREATED: "创建公司",
  TENANT_STATUS_CHANGED: "公司状态变更",
  BUSINESS_TEMPLATE_CREATED: "创建业务模板",
  BUSINESS_TEMPLATE_DRAFT_SAVED: "保存模板草稿",
  BUSINESS_TEMPLATE_PUBLISHED: "发布业务模板",
  BUSINESS_TEMPLATE_APPLIED: "应用业务模板",
  MEMBER_UPDATED: "更新成员",
  OBJECT_PUBLISHED: "发布业务表",
  RECORD_CREATED: "新增业务记录",
  RECORD_UPDATED: "更新业务记录",
  RECORD_DELETED: "删除业务记录",
};

const resourceLabels: Record<string, string> = {
  tenant: "公司",
  tenant_invitation: "成员邀请",
  tenant_member: "成员",
  business_template: "业务模板",
  object_definition: "业务表",
  record: "业务记录",
  dashboard: "仪表盘",
  dashboard_definition: "仪表盘草稿",
  dashboard_publication: "仪表盘发布版本",
  object_permission: "业务表权限",
  record_attachment: "记录附件",
  record_relation: "业务关联",
  record_follow_up: "跟进任务",

  TENANT: "公司",
  BUSINESS_TEMPLATE: "业务模板",
  TENANT_MEMBER: "成员",
  OBJECT_DEFINITION: "业务表",
  RECORD: "业务记录",
};

export function actionLabel(value: string) {
  // No half-translation for an action nobody labelled yet: "object.order updated"
  // reads as a translated label that happens to be broken. Returning the code
  // lets the caller show it once, as the raw identifier it is.
  return actionLabels[value] ?? value;
}

export function resourceLabel(value: string) {
  return resourceLabels[value] ?? value;
}
