"use client";
import { Alert, Button } from "antd";
import { useEffect, useMemo, useState } from "react";
import { DashboardCanvas } from "./dashboard-canvas";
import { previewDashboardDraft, publishDashboardDraft, saveDashboardDraft } from "./dashboard-api";
import { DashboardWidgetInspector } from "./dashboard-widget-inspector";
import { DashboardWidgetLibrary } from "./dashboard-widget-library";
import type { DashboardConfigurationView, DashboardDefinitionV2, DashboardWidgetDraft, DashboardWidgetType } from "./dashboard-types";
import styles from "./dashboard-configuration.module.css";

export function DashboardBuilder({ tenantCode, initial }: { tenantCode: string; initial: DashboardConfigurationView }) {
  const [version, setVersion] = useState(initial.draft?.draftVersion ?? 0); const [definition, setDefinition] = useState<DashboardDefinitionV2>(() => initial.draft?.draftConfiguration ?? { schemaVersion: 2, title: "工作台", widgets: [] }); const [selectedId, setSelectedId] = useState<string | undefined>(definition.widgets[0]?.id); const [savedSignature, setSavedSignature] = useState(signature(definition)); const [savedThisSession, setSavedThisSession] = useState(false); const [feedback, setFeedback] = useState<string>(); const [serverVersion, setServerVersion] = useState<number>(); const [busy, setBusy] = useState<"save" | "preview" | "publish">(); const [focusObject, setFocusObject] = useState(false);
  const dirty = signature(definition) !== savedSignature; const selected = definition.widgets.find((widget) => widget.id === selectedId); const normalizedIssues = useMemo(() => initial.issues, [initial.issues]);
  useEffect(() => { const leave = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", leave); return () => window.removeEventListener("beforeunload", leave); }, [dirty]);
  function updateWidgets(next: DashboardWidgetDraft[]) { setDefinition((current) => ({ ...current, widgets: next.map((widget, index) => ({ ...widget, sortOrder: index + 1 })) })); }
  function add(type: DashboardWidgetType) { const number = definition.widgets.filter((widget) => widget.type === type).length + 1; const widget = createWidget(type, number, definition.widgets.length + 1); updateWidgets([...definition.widgets, widget]); setSelectedId(widget.id); setFocusObject(false); }
  function copy(id: string) { const source = definition.widgets.find((widget) => widget.id === id); if (!source) return; const number = definition.widgets.filter((widget) => widget.type === source.type).length + 1; const next = { ...source, id: `${kind(source.type)}-${number}`, title: `${label(source.type)} ${number}`, sortOrder: definition.widgets.length + 1 }; updateWidgets([...definition.widgets, next]); setSelectedId(next.id); }
  async function save() { setBusy("save"); setFeedback(undefined); try { const result = await saveDashboardDraft(tenantCode, { expectedVersion: version, configuration: normalized(definition) }); setVersion(result.draftVersion); setSavedSignature(signature(definition)); setSavedThisSession(true); setFeedback("草稿已保存，尚未发布。"); } catch (error) { setServerVersion(conflictVersion(error)); setFeedback("草稿版本已变化；本地修改已保留，请重新载入后合并。"); } finally { setBusy(undefined); } }
  async function preview() { setBusy("preview"); try { await previewDashboardDraft(tenantCode, { expectedVersion: version }); setFeedback("已按保存的草稿生成预览。"); } catch { setFeedback("无法预览保存的草稿，请检查组件问题。"); } finally { setBusy(undefined); } }
  async function publish() { setBusy("publish"); try { const publication = await publishDashboardDraft(tenantCode, { expectedVersion: version }); setSavedThisSession(true); setFeedback(`工作台已发布为第 ${publication.number} 版。`); } catch { setFeedback("发布被阻止；请修复画布中的问题后重试。"); } finally { setBusy(undefined); } }
  function openIssue(id: string) { setSelectedId(id); setFocusObject(true); }
  return <div className={styles.builderPage}><header className={styles.builderHeader}><div><h1>组件化工作台</h1><p>编排已发布业务表的运营组件；保存草稿不会影响线上版本。</p></div><div className={styles.headerActions}><span>{dirty ? "有未保存修改" : `草稿版本 ${version || "未保存"}`}</span>{initial.activePublication ? <span>线上第 {initial.activePublication.number} 版</span> : <span>尚未发布</span>}<Button onClick={() => void save()} loading={busy === "save"}>保存草稿</Button><Button onClick={() => void preview()} disabled={dirty || !version} loading={busy === "preview"}>预览草稿</Button><Button type="primary" onClick={() => void publish()} disabled={dirty || !savedThisSession || !version} loading={busy === "publish"}>发布工作台</Button></div></header>{feedback ? <Alert className={styles.feedback} showIcon type="info" title={feedback} /> : null}{serverVersion ? <Alert className={styles.feedback} showIcon type="warning" title={`服务器草稿版本为 ${serverVersion}`} description="本地内容没有被覆盖。" /> : null}<div className={styles.builderLayout}><DashboardWidgetLibrary onAdd={add} widgets={definition.widgets} /><DashboardCanvas widgets={definition.widgets} selectedId={selectedId} issues={normalizedIssues} onSelect={(id) => { setSelectedId(id); setFocusObject(false); }} onIssue={openIssue} onCopy={copy} onDelete={(id) => { const next = definition.widgets.filter((widget) => widget.id !== id); updateWidgets(next); setSelectedId(next[0]?.id); }} onWidth={(id, width) => updateWidgets(definition.widgets.map((widget) => widget.id === id ? { ...widget, width } : widget))} onMove={(from, to) => { const copy = [...definition.widgets]; const [moved] = copy.splice(from, 1); copy.splice(to, 0, moved); updateWidgets(copy); }} /><DashboardWidgetInspector widget={selected} candidates={initial.candidates} focusObject={focusObject} onChange={(next) => updateWidgets(definition.widgets.map((widget) => widget.id === next.id ? next : widget))} /></div></div>;
}
function createWidget(type: DashboardWidgetType, number: number, sortOrder: number): DashboardWidgetDraft { const base = { id: `${kind(type)}-${number}`, title: `${label(type)} ${number}`, audience: "ALL" as const, objectCode: "", width: type === "METRIC" ? "QUARTER" as const : "HALF" as const, sortOrder, filters: [] }; switch (type) { case "METRIC": return { ...base, type, aggregation: "COUNT", displayFormat: "NUMBER" }; case "STATUS_DISTRIBUTION": return { ...base, type, groupByFieldKey: "", optionKeys: [], display: "BAR", aggregation: "COUNT" }; case "TREND": return { ...base, type, dateFieldKey: "", granularity: "AUTO", aggregation: "COUNT" }; case "LEADERBOARD": return { ...base, type, memberSource: "RECORD_OWNER", aggregation: "COUNT", limit: 10 }; case "RECORD_LIST": return { ...base, type, fieldKeys: ["recordNo"], sort: { field: "updatedAt", direction: "DESC" }, limit: 8 }; } }
function kind(type: DashboardWidgetType) { return { METRIC: "metric", STATUS_DISTRIBUTION: "distribution", TREND: "trend", LEADERBOARD: "leaderboard", RECORD_LIST: "records" }[type]; }
function label(type: DashboardWidgetType) { return { METRIC: "指标卡", STATUS_DISTRIBUTION: "状态分布", TREND: "趋势图", LEADERBOARD: "员工业绩排行", RECORD_LIST: "记录列表" }[type]; }
function normalized(value: DashboardDefinitionV2): DashboardDefinitionV2 { return { ...value, widgets: value.widgets.map((widget, index) => ({ ...widget, sortOrder: index + 1 })) }; }
function signature(value: DashboardDefinitionV2) { return JSON.stringify(normalized(value)); }
function conflictVersion(error: unknown): number | undefined { const maybe = error as { details?: { currentVersion?: unknown }; currentVersion?: unknown }; const value = maybe.details?.currentVersion ?? maybe.currentVersion; return typeof value === "number" ? value : undefined; }
