"use client";
import { useEffect, useRef } from "react";
import type { DashboardCandidate, DashboardWidgetDraft } from "./dashboard-types";
import styles from "./dashboard-configuration.module.css";

export function DashboardWidgetInspector({ widget, candidates, focusObject, onChange }: { widget?: DashboardWidgetDraft; candidates: DashboardCandidate[]; focusObject?: boolean; onChange: (widget: DashboardWidgetDraft) => void }) {
  const objectRef = useRef<HTMLSelectElement>(null); useEffect(() => { if (focusObject) objectRef.current?.focus(); }, [focusObject, widget?.id]);
  if (!widget) return <aside className={styles.inspector} aria-label="组件属性"><div className={styles.railHeading}><span>属性</span><small>选择画布中的组件</small></div><p className={styles.inspectorEmpty}>组件的对象、字段、聚合和受众会在这里编辑。</p></aside>;
  const candidate = candidates.find((item) => item.object.code === widget.objectCode); const fields = candidate?.fields ?? [];
  function patch(next: Partial<DashboardWidgetDraft>) { onChange({ ...widget, ...next } as DashboardWidgetDraft); }
  return <aside className={styles.inspector} aria-label="组件属性"><div className={styles.railHeading}><span>属性</span><small>{widget.type}</small></div><label>当前组件<input aria-label="当前组件" readOnly value={widget.title} /></label><label>标题<input aria-label="组件标题" value={widget.title} onChange={(event) => patch({ title: event.target.value })} /></label><label>业务表<select ref={objectRef} aria-label="业务表" value={widget.objectCode} onChange={(event) => patch({ objectCode: event.target.value })}><option value="">选择业务表</option>{candidates.map((item) => <option key={item.object.code} value={item.object.code}>{item.object.name}</option>)}</select></label><label>受众<select aria-label="组件受众" value={widget.audience} onChange={(event) => patch({ audience: event.target.value as DashboardWidgetDraft["audience"] })}><option value="ALL">所有成员</option><option value="TENANT_ADMIN">仅管理员</option><option value="EMPLOYEE">仅员工</option></select></label><label>说明<textarea aria-label="组件说明" value={widget.description ?? ""} onChange={(event) => patch({ description: event.target.value || undefined })} /></label><TypeControls widget={widget} fields={fields} onChange={onChange} /></aside>;
}
function TypeControls({ widget, fields, onChange }: { widget: DashboardWidgetDraft; fields: DashboardCandidate["fields"]; onChange: (widget: DashboardWidgetDraft) => void }) { const set = (patch: object) => onChange({ ...widget, ...patch } as DashboardWidgetDraft); const numeric = fields.filter((field) => field.type === "NUMBER" || field.type === "MONEY"); if (widget.type === "METRIC") return <><label>聚合<select aria-label="聚合方式" value={widget.aggregation} onChange={(event) => set({ aggregation: event.target.value })}><option value="COUNT">记录数</option><option value="SUM">求和</option><option value="AVG">平均值</option></select></label>{widget.aggregation !== "COUNT" ? <label>数值字段<select aria-label="数值字段" value={widget.valueFieldKey ?? ""} onChange={(event) => set({ valueFieldKey: event.target.value || undefined })}><option value="">选择字段</option>{numeric.map((field) => <option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select></label> : null}</>; if (widget.type === "STATUS_DISTRIBUTION") return <label>分组字段<select aria-label="分组字段" value={widget.groupByFieldKey} onChange={(event) => set({ groupByFieldKey: event.target.value })}><option value="">选择单选字段</option>{fields.filter((field) => field.type === "SINGLE_SELECT").map((field) => <option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select></label>; if (widget.type === "TREND") return <label>日期字段<select aria-label="日期字段" value={widget.dateFieldKey} onChange={(event) => set({ dateFieldKey: event.target.value })}><option value="">选择日期字段</option>{fields.filter((field) => field.type === "DATE" || field.type === "DATETIME").map((field) => <option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select></label>; if (widget.type === "LEADERBOARD") return <label>显示人数<input aria-label="显示人数" type="number" min="1" max="50" value={widget.limit} onChange={(event) => set({ limit: Number(event.target.value) })} /></label>; return <label>显示记录数<input aria-label="显示记录数" type="number" min="1" max="20" value={widget.limit} onChange={(event) => set({ limit: Number(event.target.value) })} /></label>; }
